---
- hosts: localhost
  vars_prompt:
    - name: domain_name
      prompt: "What is your domain name?"
      private: no
  roles:
    - create-vpc
    - create-ec2

- hosts: jenkinserver
  vars_prompt:
    - name: domain_name
      prompt: "What is your domain name?"
      private: no
  become: yes
  remote_user: ubuntu
  
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: add repo
    apt_repository:
      repo: ppa:webupd8team/java

  - name: install java8 jdk
    apt:
      name: openjdk-8-jdk

  - name: install java8 jre
    apt:
      name: openjdk-8-jdk

  - name: add key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: add jenkins repo
    apt_repository:
      repo: deb http://pkg.jenkins-ci.org/debian binary/

  - name: install jenkins
    apt:
      name: jenkins

  - name: get nginx repo
    apt_repository:
      repo: ppa:certbot/certbot

  - name: install ngxin and certbort
    apt:
      pkg:
      - nginx
      - python-certbot-nginx

  - name: copy default file
    copy:
      src: ./default
      dest: /etc/nginx/sites-available/default
      owner: root
      group: root
      mode: u=rw,g=rw,o=r

  - name: test nginx
    shell:
      cmd: nginx -t

  - name: restart nginx
    service:
      name: nginx
      state: restarted

  - name: get certificate
    shell:
      cmd: certbot --nginx -d jenkins.{{ domain_name|quote }} --email paavan014@gmail.com --agree-tos -n
