---
# tasks file for delete-vpc

# Gather facts about all VPCs
- name: List all vpcs
  ec2_vpc_net_facts:
    region: "{{region}}"
  register: all_vpc

# Gather information about all VPC route tables
- name: List all vpc route tables
  ec2_vpc_route_table_info:
    region: "{{region}}"
  register: all_vpc_route_table

# Gather information about all Network ACLs:
- name: Get All NACLs
  ec2_vpc_nacl_info:
    region: "{{region}}"
  register: all_nacls

# Gather information about all security groups
- name: Get All security groups
  ec2_group_info:
    region: "{{region}}"
  register: all_security_groups

#delete a public subnet 1
- name: delete public subnet 1
  ec2_vpc_subnet:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    cidr: "{{ subnet1_cidr }}"
    state: absent

#delete a public subnet 2
- name: delete public subnet 2
  ec2_vpc_subnet:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    cidr: "{{ subnet2_cidr }}"
    state: absent

#delete a public subnet 3
- name: delete public subnet 3
  ec2_vpc_subnet:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    cidr: "{{ subnet3_cidr }}"
    state: absent

#delete a IGW 
- name: delete Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    state: absent

#delete security group
- name: "Delete group by its id"
  ec2_group:
    region: "{{region}}"
    group_id: "{{all_security_groups.security_groups[0]['group_id']}}"
    state: absent

#delete a non-main route table 
- name: delete non-main route table 
  ec2_vpc_route_table:
    vpc_id: "{{ all_vpc.vpcs[0]['vpc_id'] }}"
    region: "{{region}}"
    route_table_id: "{{ all_vpc_route_table.route_tables[0]['id'] }}"
    lookup: id
    state: absent

#delete a vpc
- name: delete vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    state: absent
  register: my_vpc
