---
# tasks file for create_vpc
- name: create vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    state: present
  register: my_vpc

- name: create public subnet 1
  ec2_vpc_subnet:
    cidr: "{{ subnet1_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1a
    state: present

- name: create public subnet 2
  ec2_vpc_subnet:
    cidr: "{{ subnet2_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1b
    state: present

- name: create public subnet 3
  ec2_vpc_subnet:
    cidr: "{{ subnet3_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1c
    state: present

- name: create IGW
 ec2_vpc_igw:
   state: present
   vpc_id: "{{ my_vpc.vpc.id }}"
