---
# tasks file for create_vpc
- name: create vpc
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    state: present
  register: my_vpc

- name: create public subnet 1
  ec2_vpc_subnet:
    cidr: "{{ subnet1_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1a
    state: present

- name: create public subnet 2
  ec2_vpc_subnet:
    cidr: "{{ subnet2_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1b
    state: present

- name: create public subnet 3
  ec2_vpc_subnet:
    cidr: "{{ subnet3_cidr }}"
    vpc_id: "{{ my_vpc.vpc.id }}"
    az: us-east-1c
    state: present

- name: create Internet Gateway
  ec2_vpc_igw:
    state: present
    vpc_id: "{{ my_vpc.vpc.id }}"
  register: my_vpc_igw

- name: create route table
  ec2_vpc_route_table:
    vpc_id: "{{ my_vpc.vpc.id }}"
    subnets:
      - "{{ subnet1_cidr }}"
      - "{{ subnet2_cidr }}"
      - "{{ subnet3_cidr }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ my_vpc_igw.gateway_id}}"

- name: create security group
  ec2_group:
    name: ec2-sg
    description: "security group for jenkins ec2"
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    vpc_id: "{{ my_vpc.vpc.id }}"
