---
# tasks file for install-packages

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: add repo
  apt_repository:
    repo: ppa:webupd8team/java

- name: install java8 jdk
  apt:
    name: openjdk-8-jdk

- name: install java8 jre
  apt:
    name: openjdk-8-jdk

- name: add key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: add jenkins repo
  apt_repository:
    repo: deb http://pkg.jenkins-ci.org/debian binary/

- name: install jenkins
  apt:
    name: jenkins

- name: get nginx repo
  apt_repository:
    repo: ppa:certbot/certbot

- name: install ngxin and certbort
  apt:
    pkg:
    - nginx
    - python-certbot-nginx

- name: copy default file
  copy:
    src: ./default
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: test nginx
  shell:
    cmd: nginx -t

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: get certificate
  shell:
    cmd: certbot --nginx --email hemalgadhiya@gmail.com --agree-tos -n  -d jenkins.{{ domain_name|quote }}

- name: install docker
  apt:
    name: docker.io

- name: add user
  shell:
    cmd: |
      usermod -a -G docker jenkins
      usermod -a -G docker ubuntu
